/**
 * @fileoverview gRPC-Web generated client stub for vocabulary
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: vocabulary.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as vocabulary_pb from './vocabulary_pb'; // proto import: "vocabulary.proto"


export class VocabularyClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorv1VocabularyDirectoryCreateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryCreateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryCreateDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryCreateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryCreateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryCreateDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryCreateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryCreateDefaultResponse>;

  v1VocabularyDirectoryCreateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryCreateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryCreateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryCreateDefaultResponse>;

  v1VocabularyDirectoryCreateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryCreateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryCreateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryCreateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryCreateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryCreateDefault);
  }

  methodDescriptorv1VocabularyDirectoryUpdateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryUpdateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryUpdateDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryUpdateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryUpdateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryUpdateDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryUpdateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryUpdateDefaultResponse>;

  v1VocabularyDirectoryUpdateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryUpdateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryUpdateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryUpdateDefaultResponse>;

  v1VocabularyDirectoryUpdateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryUpdateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryUpdateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryUpdateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryUpdateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryUpdateDefault);
  }

  methodDescriptorv1VocabularyDirectoryDeleteDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryDeleteDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryDeleteDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryDeleteDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryDeleteDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryDeleteDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryDeleteDefault(
    request: vocabulary_pb.v1VocabularyDirectoryDeleteDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryDeleteDefaultResponse>;

  v1VocabularyDirectoryDeleteDefault(
    request: vocabulary_pb.v1VocabularyDirectoryDeleteDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryDeleteDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryDeleteDefaultResponse>;

  v1VocabularyDirectoryDeleteDefault(
    request: vocabulary_pb.v1VocabularyDirectoryDeleteDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryDeleteDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryDeleteDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryDeleteDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryDeleteDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryDeleteDefault);
  }

  methodDescriptorv1VocabularyDirectoryListDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryListDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryListDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryListDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryListDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryListDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryListDefault(
    request: vocabulary_pb.v1VocabularyDirectoryListDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryListDefaultResponse>;

  v1VocabularyDirectoryListDefault(
    request: vocabulary_pb.v1VocabularyDirectoryListDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryListDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryListDefaultResponse>;

  v1VocabularyDirectoryListDefault(
    request: vocabulary_pb.v1VocabularyDirectoryListDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryListDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryListDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryListDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryListDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryListDefault);
  }

  methodDescriptorv1VocabularyDirectoryReadDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryReadDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryReadDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryReadDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryReadDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryReadDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryReadDefault(
    request: vocabulary_pb.v1VocabularyDirectoryReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryReadDefaultResponse>;

  v1VocabularyDirectoryReadDefault(
    request: vocabulary_pb.v1VocabularyDirectoryReadDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryReadDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryReadDefaultResponse>;

  v1VocabularyDirectoryReadDefault(
    request: vocabulary_pb.v1VocabularyDirectoryReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryReadDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryReadDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryReadDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryReadDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryReadDefault);
  }

  methodDescriptorv1VocabularyDirectoryValueCreateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryValueCreateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryValueCreateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultResponse>;

  v1VocabularyDirectoryValueCreateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultResponse>;

  v1VocabularyDirectoryValueCreateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueCreateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryValueCreateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryValueCreateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryValueCreateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryValueCreateDefault);
  }

  methodDescriptorv1VocabularyDirectoryValueUpdateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryValueUpdateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryValueUpdateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultResponse>;

  v1VocabularyDirectoryValueUpdateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultResponse>;

  v1VocabularyDirectoryValueUpdateDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueUpdateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryValueUpdateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryValueUpdateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryValueUpdateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryValueUpdateDefault);
  }

  methodDescriptorv1VocabularyDirectoryValueDeleteDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryValueDeleteDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryValueDeleteDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultResponse>;

  v1VocabularyDirectoryValueDeleteDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultResponse>;

  v1VocabularyDirectoryValueDeleteDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueDeleteDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryValueDeleteDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryValueDeleteDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryValueDeleteDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryValueDeleteDefault);
  }

  methodDescriptorv1VocabularyDirectoryValueListDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryValueListDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryValueListDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryValueListDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryValueListDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryValueListDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryValueListDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueListDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryValueListDefaultResponse>;

  v1VocabularyDirectoryValueListDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueListDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueListDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryValueListDefaultResponse>;

  v1VocabularyDirectoryValueListDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueListDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueListDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryValueListDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryValueListDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryValueListDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryValueListDefault);
  }

  methodDescriptorv1VocabularyDirectoryValueReadDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyDirectoryValueReadDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyDirectoryValueReadDefaultRequest,
    vocabulary_pb.v1VocabularyDirectoryValueReadDefaultResponse,
    (request: vocabulary_pb.v1VocabularyDirectoryValueReadDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyDirectoryValueReadDefaultResponse.deserializeBinary
  );

  v1VocabularyDirectoryValueReadDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyDirectoryValueReadDefaultResponse>;

  v1VocabularyDirectoryValueReadDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueReadDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueReadDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyDirectoryValueReadDefaultResponse>;

  v1VocabularyDirectoryValueReadDefault(
    request: vocabulary_pb.v1VocabularyDirectoryValueReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyDirectoryValueReadDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyDirectoryValueReadDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyDirectoryValueReadDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyDirectoryValueReadDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyDirectoryValueReadDefault);
  }

  methodDescriptorv1VocabularyFieldCreateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyFieldCreateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyFieldCreateDefaultRequest,
    vocabulary_pb.v1VocabularyFieldCreateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyFieldCreateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyFieldCreateDefaultResponse.deserializeBinary
  );

  v1VocabularyFieldCreateDefault(
    request: vocabulary_pb.v1VocabularyFieldCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyFieldCreateDefaultResponse>;

  v1VocabularyFieldCreateDefault(
    request: vocabulary_pb.v1VocabularyFieldCreateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldCreateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyFieldCreateDefaultResponse>;

  v1VocabularyFieldCreateDefault(
    request: vocabulary_pb.v1VocabularyFieldCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldCreateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyFieldCreateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyFieldCreateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyFieldCreateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyFieldCreateDefault);
  }

  methodDescriptorv1VocabularyFieldUpdateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyFieldUpdateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyFieldUpdateDefaultRequest,
    vocabulary_pb.v1VocabularyFieldUpdateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyFieldUpdateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyFieldUpdateDefaultResponse.deserializeBinary
  );

  v1VocabularyFieldUpdateDefault(
    request: vocabulary_pb.v1VocabularyFieldUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyFieldUpdateDefaultResponse>;

  v1VocabularyFieldUpdateDefault(
    request: vocabulary_pb.v1VocabularyFieldUpdateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldUpdateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyFieldUpdateDefaultResponse>;

  v1VocabularyFieldUpdateDefault(
    request: vocabulary_pb.v1VocabularyFieldUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldUpdateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyFieldUpdateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyFieldUpdateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyFieldUpdateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyFieldUpdateDefault);
  }

  methodDescriptorv1VocabularyFieldListDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyFieldListDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyFieldListDefaultRequest,
    vocabulary_pb.v1VocabularyFieldListDefaultResponse,
    (request: vocabulary_pb.v1VocabularyFieldListDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyFieldListDefaultResponse.deserializeBinary
  );

  v1VocabularyFieldListDefault(
    request: vocabulary_pb.v1VocabularyFieldListDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyFieldListDefaultResponse>;

  v1VocabularyFieldListDefault(
    request: vocabulary_pb.v1VocabularyFieldListDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldListDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyFieldListDefaultResponse>;

  v1VocabularyFieldListDefault(
    request: vocabulary_pb.v1VocabularyFieldListDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldListDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyFieldListDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyFieldListDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyFieldListDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyFieldListDefault);
  }

  methodDescriptorv1VocabularyFieldReadDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyFieldReadDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyFieldReadDefaultRequest,
    vocabulary_pb.v1VocabularyFieldReadDefaultResponse,
    (request: vocabulary_pb.v1VocabularyFieldReadDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyFieldReadDefaultResponse.deserializeBinary
  );

  v1VocabularyFieldReadDefault(
    request: vocabulary_pb.v1VocabularyFieldReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyFieldReadDefaultResponse>;

  v1VocabularyFieldReadDefault(
    request: vocabulary_pb.v1VocabularyFieldReadDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldReadDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyFieldReadDefaultResponse>;

  v1VocabularyFieldReadDefault(
    request: vocabulary_pb.v1VocabularyFieldReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyFieldReadDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyFieldReadDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyFieldReadDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyFieldReadDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyFieldReadDefault);
  }

  methodDescriptorv1VocabularyEntityCreateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityCreateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityCreateDefaultRequest,
    vocabulary_pb.v1VocabularyEntityCreateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityCreateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityCreateDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityCreateDefault(
    request: vocabulary_pb.v1VocabularyEntityCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityCreateDefaultResponse>;

  v1VocabularyEntityCreateDefault(
    request: vocabulary_pb.v1VocabularyEntityCreateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityCreateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityCreateDefaultResponse>;

  v1VocabularyEntityCreateDefault(
    request: vocabulary_pb.v1VocabularyEntityCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityCreateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityCreateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityCreateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityCreateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityCreateDefault);
  }

  methodDescriptorv1VocabularyEntityUpdateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityUpdateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityUpdateDefaultRequest,
    vocabulary_pb.v1VocabularyEntityUpdateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityUpdateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityUpdateDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityUpdateDefault(
    request: vocabulary_pb.v1VocabularyEntityUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityUpdateDefaultResponse>;

  v1VocabularyEntityUpdateDefault(
    request: vocabulary_pb.v1VocabularyEntityUpdateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityUpdateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityUpdateDefaultResponse>;

  v1VocabularyEntityUpdateDefault(
    request: vocabulary_pb.v1VocabularyEntityUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityUpdateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityUpdateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityUpdateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityUpdateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityUpdateDefault);
  }

  methodDescriptorv1VocabularyEntityListDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityListDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityListDefaultRequest,
    vocabulary_pb.v1VocabularyEntityListDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityListDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityListDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityListDefault(
    request: vocabulary_pb.v1VocabularyEntityListDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityListDefaultResponse>;

  v1VocabularyEntityListDefault(
    request: vocabulary_pb.v1VocabularyEntityListDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityListDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityListDefaultResponse>;

  v1VocabularyEntityListDefault(
    request: vocabulary_pb.v1VocabularyEntityListDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityListDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityListDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityListDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityListDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityListDefault);
  }

  methodDescriptorv1VocabularyEntityReadDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityReadDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityReadDefaultRequest,
    vocabulary_pb.v1VocabularyEntityReadDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityReadDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityReadDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityReadDefault(
    request: vocabulary_pb.v1VocabularyEntityReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityReadDefaultResponse>;

  v1VocabularyEntityReadDefault(
    request: vocabulary_pb.v1VocabularyEntityReadDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityReadDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityReadDefaultResponse>;

  v1VocabularyEntityReadDefault(
    request: vocabulary_pb.v1VocabularyEntityReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityReadDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityReadDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityReadDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityReadDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityReadDefault);
  }

  methodDescriptorv1VocabularyEntityRecordCreateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityRecordCreateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityRecordCreateDefaultRequest,
    vocabulary_pb.v1VocabularyEntityRecordCreateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityRecordCreateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityRecordCreateDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityRecordCreateDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityRecordCreateDefaultResponse>;

  v1VocabularyEntityRecordCreateDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordCreateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordCreateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityRecordCreateDefaultResponse>;

  v1VocabularyEntityRecordCreateDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordCreateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordCreateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityRecordCreateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityRecordCreateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityRecordCreateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityRecordCreateDefault);
  }

  methodDescriptorv1VocabularyEntityRecordUpdateDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityRecordUpdateDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultRequest,
    vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityRecordUpdateDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultResponse>;

  v1VocabularyEntityRecordUpdateDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultResponse>;

  v1VocabularyEntityRecordUpdateDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordUpdateDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityRecordUpdateDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityRecordUpdateDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityRecordUpdateDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityRecordUpdateDefault);
  }

  methodDescriptorv1VocabularyEntityRecordListDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityRecordListDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityRecordListDefaultRequest,
    vocabulary_pb.v1VocabularyEntityRecordListDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityRecordListDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityRecordListDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityRecordListDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordListDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityRecordListDefaultResponse>;

  v1VocabularyEntityRecordListDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordListDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordListDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityRecordListDefaultResponse>;

  v1VocabularyEntityRecordListDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordListDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordListDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityRecordListDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityRecordListDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityRecordListDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityRecordListDefault);
  }

  methodDescriptorv1VocabularyEntityRecordReadDefault = new grpcWeb.MethodDescriptor(
    '/vocabulary.Vocabulary/v1VocabularyEntityRecordReadDefault',
    grpcWeb.MethodType.UNARY,
    vocabulary_pb.v1VocabularyEntityRecordReadDefaultRequest,
    vocabulary_pb.v1VocabularyEntityRecordReadDefaultResponse,
    (request: vocabulary_pb.v1VocabularyEntityRecordReadDefaultRequest) => {
      return request.serializeBinary();
    },
    vocabulary_pb.v1VocabularyEntityRecordReadDefaultResponse.deserializeBinary
  );

  v1VocabularyEntityRecordReadDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null): Promise<vocabulary_pb.v1VocabularyEntityRecordReadDefaultResponse>;

  v1VocabularyEntityRecordReadDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordReadDefaultRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordReadDefaultResponse) => void): grpcWeb.ClientReadableStream<vocabulary_pb.v1VocabularyEntityRecordReadDefaultResponse>;

  v1VocabularyEntityRecordReadDefault(
    request: vocabulary_pb.v1VocabularyEntityRecordReadDefaultRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: vocabulary_pb.v1VocabularyEntityRecordReadDefaultResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/vocabulary.Vocabulary/v1VocabularyEntityRecordReadDefault',
        request,
        metadata || {},
        this.methodDescriptorv1VocabularyEntityRecordReadDefault,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/vocabulary.Vocabulary/v1VocabularyEntityRecordReadDefault',
    request,
    metadata || {},
    this.methodDescriptorv1VocabularyEntityRecordReadDefault);
  }

}

